#ifndef POSTGRESQLHELPER_GLOBAL_H
#define POSTGRESQLHELPER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(POSTGRESQLHELPER_LIBRARY)
#  define POSTGRESQLHELPER_EXPORT Q_DECL_EXPORT
#else
#  define POSTGRESQLHELPER_EXPORT Q_DECL_IMPORT
#endif

#endif // POSTGRESQLHELPER_GLOBAL_H
